hz: 15
eye_level: 40
trans_target_level: 188
line_grad_th: 0.666
line_length_th: 10
close_line_th: 7
rgb_lo: [90,90,90]
rgb_hi: [255,255,255]
rect_w_lo: 170
rect_h_lo: 25
rect_h_hi: 40
whiteness_th: 1.0 #1.0 in tkb
luminance_th: 20 #50 in tkb
visualize: True
