hz: 15 #hz
eye_level: 40 #cell(v)
trans_target_level: 188 #cell(v)
stop_level: 450 #cell(v)
line_grad_th: 0.666 #y/x
line_length_th: 10 #cell(u)
close_line_th: 7 #cell
rgb_lo: [90,90,90]
rgb_hi: [255,255,255]
rect_w_lo: 170 #cell(u)
rect_h_lo: 25 #cell(v)
rect_h_hi: 40 #cell(v)
whiteness_th: 0.8 #1.0 in tkb
luminance_th: 20  #50 in tkb
visualize: True
