hz: 15
eye_level: 40
trans_target_level: 188
line_grad_th: 0.666
line_length_th: 10
close_line_th: 7
rgb_lo: [90,90,90] #[0,0,210]
rgb_hi: [255,255,255] #[180,70,255]
rect_w_lo: 170 #150
rect_h_lo: 25  #10
rect_h_hi: 40  #30
whiteness_th: 1.0
luminance_th: 50
visualize: True
